// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYkZYYdMdfxjeCuc6blt2mb-xlcJupydM',
    appId: '1:81177840526:web:052b92f6f3ea844fc4b2df',
    messagingSenderId: '81177840526',
    projectId: 'lockward-e356',
    authDomain: 'lockward-e356.firebaseapp.com',
    storageBucket: 'lockward-e356.firebasestorage.app',
    measurementId: 'G-FVZ1V0GE1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2zG8sk8EH8thckRbJTXd_BWUnTekp48',
    appId: '1:81177840526:android:4969152a30848cc8c4b2df',
    messagingSenderId: '81177840526',
    projectId: 'lockward-e356',
    storageBucket: 'lockward-e356.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vBOKiWsCJVmRGYmVL57hg8QKvrzc3oQ',
    appId: '1:81177840526:ios:df2ce6b67dcb5188c4b2df',
    messagingSenderId: '81177840526',
    projectId: 'lockward-e356',
    storageBucket: 'lockward-e356.firebasestorage.app',
    iosBundleId: 'com.finalyearproject.lockward',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vBOKiWsCJVmRGYmVL57hg8QKvrzc3oQ',
    appId: '1:81177840526:ios:df2ce6b67dcb5188c4b2df',
    messagingSenderId: '81177840526',
    projectId: 'lockward-e356',
    storageBucket: 'lockward-e356.firebasestorage.app',
    iosBundleId: 'com.finalyearproject.lockward',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYkZYYdMdfxjeCuc6blt2mb-xlcJupydM',
    appId: '1:81177840526:web:c09b8b0a4a34bbc2c4b2df',
    messagingSenderId: '81177840526',
    projectId: 'lockward-e356',
    authDomain: 'lockward-e356.firebaseapp.com',
    storageBucket: 'lockward-e356.firebasestorage.app',
    measurementId: 'G-KTQ6MQ28BP',
  );
}
